using System.Net;
using System.Text;
using System.Text.RegularExpressions;

namespace MUI.Import.Sources;

/// <summary>
/// One rendered line of an HTML page, with the colour each character was painted in and the links it
/// carried.
/// </summary>
/// <remarks>
/// Rendering to text and keeping the markup's attributes is the whole trick these two importers need.
/// Stripping tags first throws away the <c>href</c> that is the only place a website URL appears, and
/// the colour that is the only place a source's own "this value is malformed" verdict appears;
/// regexing the markup instead reads a value out of the gap between two tags, which is the mistake
/// that produces a page full of empty strings.
/// </remarks>
/// <summary>One link, and where on the line its text began.</summary>
public sealed record HtmlAnchor(int Index, string Href);

/// <inheritdoc cref="HtmlAnchor"/>
public sealed record HtmlLine(string Text, IReadOnlyList<string?> Colours, IReadOnlyList<HtmlAnchor> Anchors)
{
    /// <summary>Every link on the line, in order.</summary>
    public IEnumerable<string> Links => Anchors.Select(anchor => anchor.Href);

    /// <summary>
    /// The links whose text falls in <c>[start, end)</c>.
    /// </summary>
    /// <remarks>
    /// The reason a link's position is kept at all. On a two-column layout the first link on a line is
    /// not necessarily the one belonging to the cell being read: an <c>ICON</c> cell to the left of a
    /// <c>WEBSITE</c> cell puts a PNG first, and a reader taking the line's first <c>href</c> stores
    /// the icon as the game's website.
    /// </remarks>
    public IEnumerable<string> LinksIn(int start, int end) =>
        Anchors.Where(anchor => anchor.Index >= start && anchor.Index < end).Select(anchor => anchor.Href);

    /// <summary>The dominant colour of the non-blank characters in <c>[start, end)</c>, if any.</summary>
    public string? ColourOf(int start, int end)
    {
        string? found = null;

        for (var i = start; i < end && i < Text.Length; i++)
        {
            if (Text[i] == ' ' || Colours[i] is not { } colour)
            {
                continue;
            }

            if (found is null)
            {
                found = colour;
            }
            else if (!string.Equals(found, colour, StringComparison.Ordinal))
            {
                // Mixed. Say so by declining to answer rather than picking the first, because the
                // only caller uses this to refuse a value and a wrong guess drops a good one.
                return null;
            }
        }

        return found;
    }
}

/// <summary>
/// A deliberately small HTML reader: enough to render a <c>&lt;pre&gt;</c> page or an id-keyed
/// element to text, and nothing else.
/// </summary>
/// <remarks>
/// No HTML parser is referenced by this project, on purpose. Both sources here are fixed-shape pages
/// generated by a program, and the two things needed of them — the rendered text of a line with its
/// span colours, and the text inside one element with a known <c>id</c> — are a hundred lines that
/// can be read in full, against a dependency that would arrive with a transitive tree and a CVE feed
/// for the sake of a page of box-drawing characters.
/// </remarks>
public static partial class HtmlText
{
    private static readonly TimeSpan MatchTimeout = TimeSpan.FromSeconds(2);

    [GeneratedRegex(@"<(/?)([A-Za-z][A-Za-z0-9]*)((?:[^>""']|""[^""]*""|'[^']*')*)/?>", RegexOptions.None, 2000)]
    private static partial Regex Tag { get; }

    [GeneratedRegex(@"(?:color\s*:\s*)(#[0-9A-Fa-f]{3,6})", RegexOptions.None, 2000)]
    private static partial Regex InlineColour { get; }

    [GeneratedRegex(@"class\s*=\s*['""]([^'""]*)['""]", RegexOptions.None, 2000)]
    private static partial Regex ClassAttribute { get; }

    [GeneratedRegex(@"href\s*=\s*['""]([^'""]*)['""]", RegexOptions.None, 2000)]
    private static partial Regex HrefAttribute { get; }

    /// <summary>
    /// Renders a document line by line, keeping each line's per-character span colour and its links.
    /// </summary>
    /// <remarks>
    /// Splitting on newlines first is correct for the pages this reads because their content sits in
    /// a <c>&lt;pre&gt;</c>, where a source newline is a rendered newline. A span may still open on
    /// one line and close on another, so the colour stack is carried across lines.
    /// </remarks>
    public static IReadOnlyList<HtmlLine> RenderLines(string document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var lines = new List<HtmlLine>();
        var stack = new Stack<string?>();

        foreach (var raw in document.Split('\n'))
        {
            var text = new StringBuilder();
            var colours = new List<string?>();
            var anchors = new List<HtmlAnchor>();
            var position = 0;

            void Append(string chunk)
            {
                var decoded = WebUtility.HtmlDecode(chunk);
                text.Append(decoded);
                var colour = stack.Count > 0 ? stack.Peek() : null;
                for (var i = 0; i < decoded.Length; i++)
                {
                    colours.Add(colour);
                }
            }

            foreach (Match match in Tag.Matches(raw))
            {
                Append(raw[position..match.Index]);
                position = match.Index + match.Length;

                var closing = match.Groups[1].Value.Length > 0;
                var name = match.Groups[2].Value.ToLowerInvariant();
                var attributes = match.Groups[3].Value;

                // The index is where the link's TEXT starts, which is the character after this tag —
                // so a cell is asked "which links are inside you" by column, not by line.
                if (HrefAttribute.Match(attributes) is { Success: true } href)
                {
                    anchors.Add(new HtmlAnchor(text.Length, href.Groups[1].Value));
                }

                if (name is not "span")
                {
                    continue;
                }

                if (closing)
                {
                    if (stack.Count > 0)
                    {
                        stack.Pop();
                    }
                }
                else
                {
                    stack.Push(ColourOf(attributes));
                }
            }

            Append(raw[position..]);
            lines.Add(new HtmlLine(text.ToString().TrimEnd('\r'), colours, anchors));
        }

        return lines;
    }

    /// <summary>
    /// The rendered text inside the first element carrying <c>id="<paramref name="id"/>"</c>, or null.
    /// </summary>
    /// <remarks>
    /// <b>Keyed on the id, never on the neighbouring label.</b> On a page that lays a field out as
    /// <c>&lt;strong&gt;Address:&lt;/strong&gt;</c> in one element and its value in another, a regex
    /// anchored on the label text captures the whitespace between two closing tags and yields an
    /// empty string for every field on the page.
    /// </remarks>
    public static string? ElementTextById(string document, string id)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrEmpty(id);

        var body = Body(document, id);

        return body is null ? null : Collapse(StripTags(body));
    }

    /// <summary>The <c>href</c>s of the links inside the element carrying <paramref name="id"/>.</summary>
    public static IReadOnlyList<string> ElementLinksById(string document, string id)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrEmpty(id);

        var body = Body(document, id);
        if (body is null)
        {
            return [];
        }

        return HrefAttribute.Matches(body).Select(match => match.Groups[1].Value).ToList();
    }

    /// <summary>
    /// The inner <em>markup</em> of the first element carrying <c>id="<paramref name="id"/>"</c>, or
    /// null. The markup rather than the text, for a caller whose next question is about the rows or
    /// the links inside it.
    /// </summary>
    public static string? ElementBodyById(string document, string id)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrEmpty(id);

        return Body(document, id);
    }

    /// <summary>
    /// The inner markup of the first element whose <c>class</c> carries <paramref name="className"/>
    /// as one of its whitespace-separated tokens, or null.
    /// </summary>
    /// <remarks>
    /// Matched on a whole token so <c>mssp-data</c> does not also match <c>mssp-data-legacy</c>, and
    /// returning <em>markup</em> rather than text because the caller's next question is usually about
    /// the rows or the links inside it. Its one job here is to bound a search: a page that uses one
    /// table class for two unrelated tables — a game's MSSP readings and its player reviews — cannot
    /// be read by class alone, and the panel around the right one is what tells them apart.
    /// </remarks>
    public static string? ElementBodyByClass(string document, string className)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentException.ThrowIfNullOrEmpty(className);

        return Body(document, attributes => HasClass(attributes, className));
    }

    /// <summary>Renders markup to text, with tags removed and entities decoded.</summary>
    public static string StripTags(string markup)
    {
        ArgumentNullException.ThrowIfNull(markup);

        return WebUtility.HtmlDecode(Tag.Replace(markup, string.Empty));
    }

    /// <summary>Runs of whitespace to one space, and trimmed. Non-breaking spaces count.</summary>
    public static string Collapse(string text)
    {
        ArgumentNullException.ThrowIfNull(text);

        var builder = new StringBuilder(text.Length);
        var pendingSpace = false;

        foreach (var ch in text)
        {
            if (char.IsWhiteSpace(ch))
            {
                pendingSpace = builder.Length > 0;
                continue;
            }

            if (pendingSpace)
            {
                builder.Append(' ');
                pendingSpace = false;
            }

            builder.Append(ch);
        }

        return builder.ToString();
    }

    /// <summary>
    /// The inner markup of the first element with this id, found by counting that element's own tag
    /// name in and out again so a nested <c>&lt;div&gt;</c> does not end the search early.
    /// </summary>
    private static string? Body(string document, string id) =>
        Body(document, attributes => IdMatches(attributes, id));

    private static string? Body(string document, Func<string, bool> matches)
    {
        foreach (Match match in Tag.Matches(document))
        {
            if (match.Groups[1].Value.Length > 0)
            {
                continue;
            }

            var attributes = match.Groups[3].Value;
            if (!matches(attributes))
            {
                continue;
            }

            var name = match.Groups[2].Value;
            var start = match.Index + match.Length;
            var depth = 1;

            foreach (Match inner in Tag.Matches(document, start))
            {
                if (!string.Equals(inner.Groups[2].Value, name, StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                depth += inner.Groups[1].Value.Length > 0 ? -1 : 1;

                if (depth == 0)
                {
                    return document[start..inner.Index];
                }
            }

            return document[start..];
        }

        return null;
    }

    private static bool IdMatches(string attributes, string id)
    {
        var match = Regex.Match(attributes, @"\bid\s*=\s*['""]([^'""]*)['""]", RegexOptions.None, MatchTimeout);

        return match.Success && string.Equals(match.Groups[1].Value, id, StringComparison.Ordinal);
    }

    private static bool HasClass(string attributes, string className)
    {
        if (ClassAttribute.Match(attributes) is not { Success: true } match)
        {
            return false;
        }

        return match.Groups[1].Value
            .Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Contains(className, StringComparer.Ordinal);
    }

    /// <summary>
    /// A span's colour, whether it was written inline or as one of the page's own palette classes.
    /// </summary>
    /// <remarks>
    /// The TinTin mudlist emits both spellings on the same page — its legend uses <c>class='l31'</c>
    /// and its data rows use <c>style='color:#F55'</c> — for what is one colour, so both must reduce
    /// to the same key or the legend cannot be matched against the rows it explains.
    /// </remarks>
    private static string? ColourOf(string attributes)
    {
        if (InlineColour.Match(attributes) is { Success: true } inline)
        {
            return Normalise(inline.Groups[1].Value);
        }

        if (ClassAttribute.Match(attributes) is { Success: true } klass)
        {
            return AnsiPalette.ColourOfClass(klass.Groups[1].Value);
        }

        return null;
    }

    private static string Normalise(string colour)
    {
        var upper = colour.ToUpperInvariant();

        // #RRGGBB written with repeated nibbles is the same colour as #RGB. The mudlist's stylesheet
        // uses the short form and its inline styles use the long one.
        if (upper.Length == 7
            && upper[1] == upper[2] && upper[3] == upper[4] && upper[5] == upper[6])
        {
            return $"#{upper[1]}{upper[3]}{upper[5]}";
        }

        return upper;
    }
}

/// <summary>
/// The sixteen-colour palette a terminal-to-HTML converter emits, in both spellings it emits it in.
/// </summary>
public static class AnsiPalette
{
    private static readonly Dictionary<string, string> ByClass = new(StringComparer.Ordinal)
    {
        ["d30"] = "#000", ["l30"] = "#555",
        ["d31"] = "#B00", ["l31"] = "#F55",
        ["d32"] = "#0B0", ["l32"] = "#5F5",
        ["d33"] = "#BB0", ["l33"] = "#FF5",
        ["d34"] = "#00B", ["l34"] = "#55F",
        ["d35"] = "#B0B", ["l35"] = "#F5F",
        ["d36"] = "#0BB", ["l36"] = "#5FF",
        ["d37"] = "#BBB", ["l37"] = "#FFF",
        ["d38"] = "#FFF", ["l38"] = "#FFF",
        ["d39"] = "#FFF", ["l39"] = "#FFF",
    };

    public static string? ColourOfClass(string classNames)
    {
        ArgumentNullException.ThrowIfNull(classNames);

        foreach (var name in classNames.Split(' ', StringSplitOptions.RemoveEmptyEntries))
        {
            if (ByClass.TryGetValue(name, out var colour))
            {
                return colour;
            }
        }

        return null;
    }
}
